### ISSUE TITLE
https://github.com/hoaproject/Ruler has been archived

### ISSUE THREAD

**Issue by marclaporte** [hiqdev/php-billing#33]
"I've archived all Hoa's repositories on Github, along with Packagist."

Source: https://twitter.com/mnt_io/status/1439871569522737157

**Comment by hiqsol** [comment]
Thank you for the information!
We'll find some solution. Do you have any ideas?

**Comment by marclaporte** [comment]
Sorry, no idea.

**Comment by marclaporte** [comment]
At least 5 projects are reported to be using this, so let's keep an eye on https://github.com/hoaproject/Ruler/network/members and I predict someone will continue the project (not the whole Hoa project, but this component)

**Comment by marclaporte** [comment]
Another project, but with low activity:
https://github.com/bobthecow/Ruler/commits/master

**Comment by SilverFire** [comment]
As I see on a Network graph, people just randomly fork the repo, fix something that bothers them right away and use it as-is even without publishing to Packagist.

> I predict someone will continue the project (not the whole Hoa project, but this component)

I guess it will be me =\

**Comment by marclaporte** [comment]
Done:
- https://github.com/hiqdev/hoa-ruler
- https://packagist.org/packages/hiqdev/hoa-ruler
